# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class PagedAttentionBackend(Protocol):
    def initialize(self, num_blocks: int) -> None: ...
    def patch_model(self, model: Any) -> int: ...
    def warm_up(self) -> None: ...
    def num_blocks(self) -> int: ...
